### PR TITLE
Added Ayu Dark Orange based on teabyii's version of Ayu Dark

### PR DESCRIPTION
**Pull request by FullstopCoding**
Apologies for some of the formatting (VS Code addon I'm sure), but here is another theme for the addon based on teabyii's Ayu Dark.

### CODE REVIEW

**Comment by swashata** [comment]
Hi,

Thanks for the contribution. How exactly did you make the theme? I don't see any color scheme added to the schemes. What you need to do is

1. Go to https://github.com/swashata/vscode-beautiful-ui/tree/master/src/schemes and add `AyuDarkOrange.js` file.
2. Copy over the content from https://github.com/swashata/vscode-beautiful-ui/blob/master/src/schemes/Template.noop.js to your new `AyuDarkOrange.js` file.
3. Edit the colors.
4. Edit https://github.com/swashata/vscode-beautiful-ui/blob/master/src/colors.js and put `'Ayu Dark Orange': require('./schemes/AyuDarkOrange')` at the end of the list.
5. Run `yarn install && yarn build`.
6. Check the generated color theme.

So you shouldn't edit `themes/Ayu Dark Orange-color-theme.json` by hand as it should be autogenerated.

**Comment by FullstopCoding** [comment]
Ah...I just took a copy of your Ayu Dark theme and modified the colours, and then modified the packages.json file to include my JSON file!

**Comment by swashata** [comment]
Better, you copy `src/schemes/AyuDark.js` to `src/schemes/AyuDarkOrange.js` and make changes over there and do the steps above.

The theme files are not really hand-made. Those are just generated through a simple build https://github.com/swashata/vscode-beautiful-ui/blob/master/script/generateTheme.js

**Comment by swashata** [comment]
Hey, I just published a bunch of new themes. Also fixed some issues with the old ones. Can you please rebase your work with the new changes if you are still interested.

**Comment by FullstopCoding** [comment]
It looks like items in my theme use very specific colours for the tokens.  Do I just explicitly state all the tokens for the theme?

**Comment by swashata** [comment]
Hi,

With current build system that isn't possible 🙁. I will change it a bit to accept specified token colors and override the existing ones. Let's give it a look over next weekend

**Comment by swashata** [comment]
Hi,

After giving thought, I think it is best if you publish your theme separately. The color patterns are too much different from what this engine gives.

If you need help publishing your theme, do let me know.

**Pull request closed without merging**
